# Nome da Aplicação
spring.application.name=ChurnInsight

# --- Configuração do Banco de Dados (PostgreSQL) ---
# 'db' é o nome do serviço no docker-compose. '5432' é a porta padrão.
spring.datasource.url=jdbc:postgresql://localhost:5432/churn_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (Cria as tabelas automaticamente baseadas nas classes Java)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração de Logging
logging.level.com.ficaai.backend=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Configuração do Servidor
python.api.url=http://localhost:8000/predict
python.api.usar-mock=false
server.port=8080
