version: '3.8'

services:
  # --- 1. BANCO DE DADOS (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: ficaai-postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=churn_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hackathon-net

  # --- 2. BACKEND JAVA ---
  backend:
    container_name: ficaai-backend
    build: ./backend-main/
    ports:
      - "8080:8080"
    restart: always
    environment:
      # Sobrescreve o application.properties para funcionar no Docker
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/churn_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # Conexão com Python (Nome do container, não localhost)
      - PYTHON_API_URL=http://data-science-api:8000/predict
      - PYTHON_API_USAR_MOCK=false
    networks:
      - hackathon-net
    depends_on:
      - db
      - data-science-api

  # --- 3. PYTHON API (Data Science) ---
  data-science-api:
    container_name: ficaai-python
    build: ./data-science/
    ports:
      - "8000:8000"
    volumes:
      - ./data-science/data:/app/data
    networks:
      - hackathon-net

  # --- 4. FRONTEND (React) ---
  frontend:
    container_name: ficaai-frontend
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - hackathon-net
    environment:
      # O navegador do usuário (fora do docker) precisa acessar o java na 8080
      - VITE_API_URL=http://localhost:8080

networks:
  hackathon-net:
    driver: bridge

volumes:
  pgdata: